project:
  type: website
  render: # Add HERE new chapters and new notebooks
    - index.qmd
    - chapters/cluster1.qmd
    - chapters/cluster2.qmd
    - chapters/cluster3.qmd
    - chapters/cluster4.qmd
    - chapters/cluster5.qmd
    - chapters/howContribute.qmd


website:
  page-navigation: true
  title: "Template for training resources in Python"
  site-url: "https://github.com/AIML4OS/WP10_template_quarto_python_test/"
  repo-url: "https://github.com/AIML4OS/WP10_template_quarto_python_test"
  repo-actions: [edit, source, issue]
  sidebar:
    search: true
    contents: # Add HERE new chapters (but not the notebooks)
      - href: index.qmd
        text: Introduction
      - href: chapters/cluster1.qmd
        text: Cluster 1 Overview
      - href: chapters/cluster2.qmd
        text: Cluster 2 Overview
      - href: chapters/cluster3.qmd
        text: Cluster 3 Overview
      - href: chapters/cluster4.qmd
        text: Cluster 4 Overview
      - href: chapters/cluster5.qmd
        text: Cluster 5 Overview
      - href: chapters/howContribute.qmd
        text: How to contribute?

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true
  ipynb:
    output: true


filters:
  - export-metadata.lua

